// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLI4tEc8YTDspPqfQksdu6vccrnulia2o',
    appId: '1:771780416047:android:54781aa5aa899e90396cda',
    messagingSenderId: '771780416047',
    projectId: 'sep490-bf12d',
    storageBucket: 'sep490-bf12d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMDZBp7Iz-xikz-dn8GPu_U4Ux_YN6jUg',
    appId: '1:771780416047:ios:003885a9e821cc41396cda',
    messagingSenderId: '771780416047',
    projectId: 'sep490-bf12d',
    storageBucket: 'sep490-bf12d.firebasestorage.app',
    androidClientId: '771780416047-52coue4efejft31304qjpbu5fa99g83d.apps.googleusercontent.com',
    iosClientId: '771780416047-0jb1ekona6i63hcade073s1277tgd4un.apps.googleusercontent.com',
    iosBundleId: 'com.example.spaMobile',
  );

}